---
- hosts: localhost
  remote_user: joe
  become: yes
  tasks:
    - name: install desktop applications
      apt:
        update_cache: yes
        state: latest
        autoclean: yes
        pkg:
        - krdc
        - yakuake
        - gconf2
        - gconf-service
        - gvfs-bin
        - libappindicator1
        - keepassxc
    - name: install Slack
      debug:
        msg: Update with actual install details
    - name: install vscode
      debug:
        msg: update with actual install details

