---
### playbook currently works only for Ubuntu 16.04/19.04, and possibly Debian based distros
### required vars and defaults:  
  # folding_slot_control: medium
  # folding_donor: anonymous
  # folding_team: 0 (this indicates no team)
  # folding_control_node: client accessible from localhost only
  # use_cpu: false
  # gpu_list: (default is no GPU slots)
  # fahclient_current_version: (required, download from https://foldingathome.org/start-folding/)
- hosts: folding
  become: yes
  tasks:
  - name: install opencl-dev
    apt:
      name: nvidia-opencl-dev
      state: latest
  - name: install cuda tools
    apt:
      name: nvidia-cuda-toolkit
      state: latest

  - name: install remaining dependencies
  # from current 18.04 ubuntu: nvidia-libopencl1-384 nvidia-384-dev nvidia-384 libcuda1-384 python3-pycuda python-pycuda nvidia-cuda-toolkit
    apt:
      name:
      - freeglut3
      - libgl1-mesa-glx
      - dh-python
      - python-gtk2
      - ocl-icd-opencl-dev
      state: present

  - name: copy folding client from ansible server
    copy:
      src: "{{ fahclient_current_version }}"
      dest: /tmp/fahclient_current.deb

  - name: install folding client
    apt:
      deb: /tmp/fahclient_current.deb
      state: present
    notify: fahclient_service

  - name: update configuration file
    template:
      src: templates/fahclient-config.xml.j2
      dest: /etc/fahclient/config.xml
    notify: fahclient_service

  handlers:
  - name: fahclient service restart
    sysvinit:
      name: FAHClient
      enabled: yes
      state: restarted
    listen: fahclient_service
