---
- hosts: webservers
  remote_user: joe
  become: yes
  include:
    - 
  tasks:
    - name: download and extract glpi archive 
      unarchive:
        src: https://github.com/glpi-project/glpi/releases/download/9.4.4/glpi-9.4.4.tgz
        dest: /var/www/html
       