---
- hosts: localhost
  vars:
    - vagrant_ver: 2.2.7
  tasks:
    - name: install required packages for kvm
      become: yes
      apt:
        name:
        - qemu-kvm
        - libvirt-dev
        - virt-top
        - libguestfs-tools
        - virtinst
        - bridge-utils        
    - name: load kvm kernel module at boot (kvm modules will need to be loaded manually if needed before reboot)
      become: yes
      lineinfile:
        path: /etc/modules
        line: vhost_net
      
    - name: download vagrant from hashicorp
      become: yes
      get_url:
        url: "https://releases.hashicorp.com/vagrant/{{ vagrant_ver }}/vagrant_{{ vagrant_ver }}_x86_64.deb"
        dest: /tmp/vagrant_current.deb
        
    - name: install vagrant from downloaded .deb file
      become: yes
      apt: 
        deb: /tmp/vagrant_current.deb
        state: present
        dpkg_options: force-depends,force-confdef,force-confold

    - name: install vagrant libvirt plugin
      command: vagrant plugin install vagrant-libvirt
      register: plugin_results

    - name: output the vagrant-libvirt plugin installation results
      debug:
        msg: "{{ plugin_results }}"
