---
- hosts: localhost
  become: yes
  vars:
    - vagrant_ver: 2.2.7
  tasks:
    - name: install required packages for kvm
      apt:
        name:
        - qemu-kvm
        - libvirt-dev
        - virt-top
        - libguestfs-tools
        - virtinst
        - bridge-utils        
    - name: load kvm kernel module at boot (kvm modules will need to be loaded manually if needed before reboot)
      lineinfile:
        path: /etc/modules
        line: vhost_net
      
    - name: download vagrant from hashicorp
      get_url:
        url: "https://releases.hashicorp.com/vagrant/{{ vagrant_ver }}/vagrant_{{ vagrant_ver }}_x86_64.deb"
        dest: /tmp/vagrant_current.deb
      notify: install vagrant

    - name: install vagrant libvirt plugin
      command: vagrant plugin install vagrant-libvirt
      register: plugin_results

    - name: output the vagrant-libvirt plugin installation results
      debug:
        msg: "{{ plugin_results }}"


  handlers:
    name: install vagrant from downloaded .deb file
    apt: 
      deb: /tmp/vagrant_current.deb
      state: latest
      dpkg_options: 
      - force-depends
      - force-confdef
      - force-confold
    listen: install vagrant
