---
- hosts: zabbix_servers
  become: yes
  # var_files:
    # - secrets/zabbix.yml
  pre_tasks:
    - name: install pip3 package
      apt:
        name: python3-pip
        state: present
    - name: install required python library
      pip:
        name: pymysql
        state: present
  roles:
    - sparknsh.mariadb
    - dj-wasabi.zabbix-server
    - dj-wasabi.zabbix-web
    - dj-wasabi.zabbix-agent